### ISSUE TITLE
InfografiaHilos

### ISSUE THREAD

**Issue by ElisabetRD** [SistemasTecTlaxiaco/infografia-de-hilos-ElisabetRD#2]
[Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-ElisabetRD/files/15118651/Hilos.pdf)

**Comment by AricelCastro** [comment]
nuestro equipo le da una caliicacion de 19/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
